### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by HeyImPorky** [doookkie/auternos#8]
Please Make A Video Tutorial Cause i Dont Really Know How To Code So Its Hard For Me. A video tutorial of how to set the thing up + how to deploy on heroku

**Comment by HeyImPorky** [comment]
And where do i run the code

**Comment by HeyImPorky** [comment]
Thanks

**Comment by ddomino007** [comment]
You don't need to code anything.
This is code ready to use, the instructions are in the readme.

**Comment by HeyImPorky** [comment]
Ok thanks

**Comment by HeyImPorky** [comment]
But where do i run the code

**Comment by HeyImPorky** [comment]
Where do i Run it 24/7?

**Comment by ddomino007** [comment]
Locally
